# Generated by Django 2.2.6 on 2019-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.AddField(
            model_name='project',
            name='imgUrl',
            field=models.CharField(default='about/images/lastStand.png', max_length=30),
            preserve_default=False,
        ),
    ]
